name: 'Create a .env file'
author: 'Miguel da Mota'
inputs:
  env:
    description: 'Environment variables'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
outputs:
  path:
    description: Path to the created file
